### ISSUE TITLE
輸出的作法

### ISSUE THREAD

**Issue by arnoldlan** [ICD20/hw4#4]
助教不好意思，hw4的code generation是用fprintf() 直接把java bytecode寫到test/assembly裏面的一個檔案嗎？

**Comment by nobodyzxc** [comment]
https://github.com/ICD20/hw4/blob/a286d57afeb74667f9be6586dbc4b3921ee36d2f/parser.y#L79-L91
我們會給 option，你可以 extern char *output 然後寫到這個檔名就好了。
可以參考一下 README 的作法。
```
PASS_HANDLE(codegen, ProgNode      , node){
  char fn[128];
  prog = node->name;
  sprintf(fn, "%s.s", node->name);
  fd = fopen(output ? output : fn, "w");
  gen(";gen code into the file\n");
  fclose(fd);
}
```
如果不是 NULL 就寫參數給的 filename，如果是 NULL 就自訂一個 filename （測試會給參數 filename）

如果你有拿 sample code 的話，直接執行，他應該會輸出一個用 program name 當作檔名的 file。
如果給 filename 參數就會以參數生成該檔名。

**Comment by arnoldlan** [comment]
ok 助教謝謝！！
